# Generated by Django 5.1.7 on 2025-03-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceriespricechecker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grocery',
            name='quantity',
        ),
        migrations.AddField(
            model_name='grocery',
            name='barcode_api_last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grocery',
            name='barcode_lookup_failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grocery',
            name='barcode_number',
            field=models.CharField(default='', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grocery',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='grocery',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='grocery',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grocery',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grocery',
            name='manually_entered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grocery',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='grocery',
            name='store_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='grocery',
            name='store_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='grocery',
            name='store_price_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grocery',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
