# Generated by Django 5.1.7 on 2025-03-24 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceriespricechecker', '0002_remove_grocery_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery',
            name='barcode_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
