# Generated by Django 5.1.7 on 2025-04-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceriespricechecker', '0005_price_shop_priceshop_shoppinglist_usergrocery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('origin', models.CharField(max_length=255)),
            ],
        ),
    ]
