# Generated by Django 5.1.7 on 2025-04-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceriespricechecker', '0006_emaillist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillist',
            name='email',
            field=models.EmailField(error_messages={'unique': 'We appreciate your interest, however this email has already been submitted.'}, max_length=254, unique=True),
        ),
    ]
