# Generated by Django 5.1.7 on 2025-04-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceriespricechecker', '0007_alter_emaillist_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
